apiVersion: v1
kind: Pod
metadata:
  name: client-1-deployment
spec:
  restartPolicy: Never
  containers:
  - name: client-1
    image: client-1:v1.2
    imagePullPolicy: Never
    env:
    - name: POD_IP
      value: $POD_IP
