apiVersion: v1
kind: Pod
metadata:
  name: trigger-rest-deployment
spec:
  restartPolicy: Never
  containers:
  - name: trigger-rest
    image: trigger-rest:v1.2
    imagePullPolicy: Never
    env:
    - name: POD_IP
      value: $POD_IP
